// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzqxkyuwljmofarnfufd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cXhreXV3bGptb2Zhcm5mdWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTgyNDYsImV4cCI6MjA1OTIzNDI0Nn0.PFlt5sm6tonK63Gj-g5yjGxKR6LN2MPOGnSgZaSg2D4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);